name: Run Go Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19 # Set this to the version of Go you are using

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
