name: Run Go Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Go version
        run: go version

      - name: Set up dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test -v ./...
